<?php

/**
 * BaseSymlinkResizer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    jim-link
 * @subpackage model
 * @author     Anthony Regeda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSymlinkResizer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('symlink_resizer');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}