<?php

/**
 * BaseSymlink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $link_id
 * @property Link $Link
 * 
 * @method string  getId()      Returns the current record's "id" value
 * @method integer getLinkId()  Returns the current record's "link_id" value
 * @method Link    getLink()    Returns the current record's "Link" value
 * @method Symlink setId()      Sets the current record's "id" value
 * @method Symlink setLinkId()  Sets the current record's "link_id" value
 * @method Symlink setLink()    Sets the current record's "Link" value
 * 
 * @package    jim-link
 * @subpackage model
 * @author     Anthony Regeda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSymlink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('symlink');
        $this->hasColumn('id', 'string', 9, array(
             'type' => 'string',
             'primary' => true,
             'length' => 9,
             ));
        $this->hasColumn('link_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));


        $this->index('fresh', array(
             'fields' => 
             array(
              'created_at' => 
              array(
              'sorting' => 'DESC',
              ),
             ),
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Link', array(
             'local' => 'link_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}