<?php

/**
 * Link
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    jim-link
 * @subpackage model
 * @author     Anthony Regeda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Link extends BaseLink
{
  /**
   * Set url hash before insert
   * @param Doctrine_Event $event
   */
  public function preInsert($event)
  {
    $link = $event->getInvoker();
    /* @var $link Link */
    $link->hash = md5($link->url);
  }

  /**
   * Reset url hash before update
   * @param Doctrine_Event $event
   */
  public function preUpdate($event)
  {
    $link = $event->getInvoker();
    /* @var $link Link */
    $modified = $link->getModified();
    if (isset($modified[$link->getTable()->getFieldName('url')])) {
      $link->hash = md5($link->url);
    }
    else {
      $event->skipOperation();
    }
  }

  /**
   * Validate a link
   */
  protected function validate()
  {
    if (filter_var($this->url, FILTER_VALIDATE_URL)) {
      $fragments = parse_url($this->url);
      if (isset($_SERVER['HTTP_HOST'])) {
        $input = $fragments['host'];
        $origin = $_SERVER['HTTP_HOST'];
        if (false !== strpos($origin, $input) || false !== strpos($input, $origin)) {
          goto error;
        }
      }
      return;
    }
    error:
    $this->getErrorStack()->add('url', 'url');
  }
}