<?php

/**
 * LinkTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Link');
    }

    /**
     * Find a link by URL
     * @param string $url
     * @return Link
     */
    public function findOneByUrl($url)
    {
      return $this->findOneByHash(md5($url));
    }

    /**
     * Creates a short link
     * @param string $url
     * @return Symlink
     */
    public function createSymlink($url)
    {
      $symlink = new Symlink();
      $link = new Link();
      $link->url = $url;
      $link->Symlinks[] = $symlink;
      try {
        $link->save();
      }
      catch (Doctrine_Connection_Exception $e) {
        $link = $this->findOneByUrl($url);
        $link->Symlinks[] = $symlink;
        $link->save();
      }
      return $symlink;
    }
}