<?php

/**
 * Symlink
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    jim-link
 * @subpackage model
 * @author     Anthony Regeda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Symlink extends BaseSymlink
{
  /**
   * Symlink key is created after primary key
   * @param Doctrine_Event $event
   */
  public function preInsert($event)
  {
    $symlink = $event->getInvoker();
    /* @var $symlink Symlink */
    $resizer = new SymlinkResizer();
    $resizer->save();
    $symlink->id = base_convert($resizer->id, 10, 36).base_convert(mt_rand(36, 1295), 10, 36);
  }
}
