<?php

/**
 * SymlinkResizer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jim-link
 * @subpackage model
 * @author     Anthony Regeda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SymlinkResizer extends BaseSymlinkResizer
{
}
