<?php

/**
 * SymlinkResizerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SymlinkResizerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SymlinkResizerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SymlinkResizer');
    }
}