<?php

/**
 * SymlinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SymlinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SymlinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Symlink');
    }
}